"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import type { ReasoningStep } from "@/lib/types";

interface Props {
  reasoningSteps: ReasoningStep[];
  eventId?: string;
}

export default function ExportMenu({ reasoningSteps, eventId }: Props) {
  const [open, setOpen] = useState(false);
  const [toast, setToast] = useState<string | null>(null);
  const ref = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const handler = (e: MouseEvent) => {
      if (ref.current && !ref.current.contains(e.target as Node)) setOpen(false);
    };
    document.addEventListener("mousedown", handler);
    return () => document.removeEventListener("mousedown", handler);
  }, []);

  const showToast = (msg: string) => {
    setToast(msg);
    setTimeout(() => setToast(null), 3000);
  };

  const downloadJSON = useCallback(() => {
    const blob = new Blob([JSON.stringify(reasoningSteps, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "reasoning_log.json";
    a.click();
    URL.revokeObjectURL(url);
    setOpen(false);
  }, [reasoningSteps]);

  const downloadCSV = useCallback(() => {
    const header = "id,agent,stepType,description,timestamp,severity\n";
    const rows = reasoningSteps.map((s) =>
      `"${s.id}","${s.agent}","${s.stepType}","${s.description.replace(/"/g, '""')}",${s.timestamp},"${s.severity || ""}"`
    ).join("\n");
    const blob = new Blob([header + rows], { type: "text/csv" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "reasoning_log.csv";
    a.click();
    URL.revokeObjectURL(url);
    setOpen(false);
  }, [reasoningSteps]);

  const downloadPDF = useCallback(async () => {
    // Client-side PDF generation using jsPDF
    try {
      const { default: jsPDF } = await import("jspdf");
      const doc = new jsPDF();
      const margin = 20;
      let y = margin;

      doc.setFontSize(18);
      doc.setFont("helvetica", "bold");
      doc.text("Meridian Intelligence Platform", margin, y);
      y += 8;
      doc.setFontSize(12);
      doc.setFont("helvetica", "normal");
      doc.text("Disruption Impact Report", margin, y);
      y += 12;

      doc.setDrawColor(42, 48, 56);
      doc.line(margin, y, 190, y);
      y += 10;

      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.text("Executive Summary", margin, y);
      y += 8;
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.text("Event: Typhoon Gaemi — Malacca Strait Disruption", margin, y); y += 6;
      doc.text("Severity: CRITICAL (0.92)", margin, y); y += 6;
      doc.text("Corridor: Asia-Europe (Malacca / Suez)", margin, y); y += 6;
      doc.text(`Generated: ${new Date().toISOString()}`, margin, y); y += 12;

      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.text("Cascade Analysis", margin, y);
      y += 8;
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      const cascades = [
        "Singapore: +2 days delay, 47 vessels (LONG_TAIL congestion)",
        "Colombo: +3 days delay, 18 vessels (HIGH congestion)",
        "Chennai: +3.5 days delay, 12 vessels (MEDIUM congestion)",
        "JNPT Mumbai: +4 days delay, 21 vessels (HIGH congestion)",
        "Port Said: +5 days delay, 15 vessels (MEDIUM congestion)",
      ];
      for (const line of cascades) {
        doc.text(`  - ${line}`, margin, y); y += 6;
      }
      y += 6;

      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.text("Route Alternatives", margin, y);
      y += 8;
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.text("1. Lombok Strait bypass: +18h, +$12,000, Risk: LOW (RECOMMENDED)", margin, y); y += 6;
      doc.text("2. Hold at anchorage: +72h, $0, Risk: LOW", margin, y); y += 6;
      doc.text("3. Sunda Strait bypass: +24h, +$8,000, Risk: HIGH", margin, y); y += 12;

      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.text("Agent Reasoning Trace", margin, y);
      y += 8;
      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      for (const step of reasoningSteps.slice(0, 15)) {
        if (y > 270) { doc.addPage(); y = margin; }
        const ts = `${Math.floor(step.timestamp / 1000)}s`;
        doc.text(`[${ts}] ${step.agent.toUpperCase()}: ${step.description}`, margin, y);
        y += 5;
      }

      y += 8;
      doc.setDrawColor(42, 48, 56);
      doc.line(margin, y, 190, y);
      y += 6;
      doc.setFontSize(8);
      doc.text("Generated by Meridian | Powered by Google ADK + Gemini", margin, y);

      doc.save(`meridian-report-${eventId || "evt_7f3a"}.pdf`);
      setOpen(false);
    } catch {
      showToast("PDF generation unavailable");
      setOpen(false);
    }
  }, [reasoningSteps, eventId]);

  const copyLink = useCallback(() => {
    navigator.clipboard.writeText(window.location.href).then(() => {
      showToast("Link copied");
    });
    setOpen(false);
  }, []);

  return (
    <div ref={ref} className="relative">
      <button
        onClick={() => setOpen(!open)}
        className="btn-ghost p-2 rounded-lg"
        aria-label="Export and share"
      >
        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <path d="M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8" />
          <polyline points="16 6 12 2 8 6" />
          <line x1="12" y1="2" x2="12" y2="15" />
        </svg>
      </button>

      {open && (
        <div
          className="absolute right-0 top-full mt-1 w-56 rounded-lg py-1 z-50 animate-slide-up"
          style={{
            background: "var(--bg-surface-1)",
            border: "1px solid var(--border)",
            boxShadow: "0 8px 30px rgba(0,0,0,0.4)",
          }}
        >
          <button onClick={downloadPDF} className="w-full text-left px-3 py-2 text-xs flex items-center gap-2 transition-colors" style={{ color: "var(--text-secondary)" }}
            onMouseEnter={(e) => { e.currentTarget.style.background = "var(--bg-surface-2)"; }}
            onMouseLeave={(e) => { e.currentTarget.style.background = "transparent"; }}>
            Download PDF Report
          </button>
          <button onClick={downloadJSON} className="w-full text-left px-3 py-2 text-xs flex items-center gap-2 transition-colors" style={{ color: "var(--text-secondary)" }}
            onMouseEnter={(e) => { e.currentTarget.style.background = "var(--bg-surface-2)"; }}
            onMouseLeave={(e) => { e.currentTarget.style.background = "transparent"; }}>
            Export Reasoning (JSON)
          </button>
          <button onClick={downloadCSV} className="w-full text-left px-3 py-2 text-xs flex items-center gap-2 transition-colors" style={{ color: "var(--text-secondary)" }}
            onMouseEnter={(e) => { e.currentTarget.style.background = "var(--bg-surface-2)"; }}
            onMouseLeave={(e) => { e.currentTarget.style.background = "transparent"; }}>
            Export Reasoning (CSV)
          </button>
          <div style={{ borderTop: "1px solid var(--border)", margin: "4px 0" }} />
          <button onClick={copyLink} className="w-full text-left px-3 py-2 text-xs flex items-center gap-2 transition-colors" style={{ color: "var(--text-secondary)" }}
            onMouseEnter={(e) => { e.currentTarget.style.background = "var(--bg-surface-2)"; }}
            onMouseLeave={(e) => { e.currentTarget.style.background = "transparent"; }}>
            Copy Link
          </button>
        </div>
      )}

      {toast && <div className="toast">{toast}</div>}
    </div>
  );
}
